-- =============================================================
--  V1__schema.sql  –  Schema inicial do AcadTrack
--  Banco: H2 2.x (modo arquivo, ENUM nativo)
--  Ordem de criação respeita dependências de chave estrangeira
-- =============================================================

-- -------------------------------------------------------
-- Tabelas sem dependências externas
-- -------------------------------------------------------

CREATE TABLE turma (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255)
);

CREATE TABLE responsavel (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR(255),
    email VARCHAR(255)
);

CREATE TABLE disciplina (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome   VARCHAR(255),
    status ENUM('ATIVA', 'INATIVA')
);

CREATE TABLE simulado (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(255)
);

-- -------------------------------------------------------
-- Aluno — referencia responsavel e turma
-- -------------------------------------------------------

CREATE TABLE aluno (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                            VARCHAR(255),
    email                           VARCHAR(255),
    turma_id                        BIGINT,
    responsavel_id                  BIGINT,
    vinculo_responsavel_ativo       BOOLEAN,
    permissao_visualizar_notas      BOOLEAN,
    permissao_visualizar_simulados  BOOLEAN,
    permissao_visualizar_desempenho BOOLEAN,
    ativo                           BOOLEAN,
    media_atual                     FLOAT(53),
    situacao_academica              ENUM('APROVADO', 'RECUPERACAO', 'REPROVADO'),
    CONSTRAINT uq_aluno_email       UNIQUE (email),
    CONSTRAINT fk_aluno_responsavel FOREIGN KEY (responsavel_id) REFERENCES responsavel (id),
    CONSTRAINT fk_aluno_turma       FOREIGN KEY (turma_id)       REFERENCES turma (id)
);

-- -------------------------------------------------------
-- Composição de simulados (simulado → disciplinas + pesos)
-- -------------------------------------------------------

CREATE TABLE simulado_disciplina (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    simulado_id   BIGINT,
    disciplina_id BIGINT,
    peso          FLOAT(53) NOT NULL,
    CONSTRAINT fk_simulado_disciplina_simulado FOREIGN KEY (simulado_id) REFERENCES simulado (id)
);

-- -------------------------------------------------------
-- Nota lançada (aluno × simulado × disciplina)
-- -------------------------------------------------------

CREATE TABLE nota (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id      BIGINT,
    simulado_id   BIGINT,
    disciplina_id BIGINT,
    valor         FLOAT(53) NOT NULL,
    CONSTRAINT fk_nota_aluno      FOREIGN KEY (aluno_id)      REFERENCES aluno (id),
    CONSTRAINT fk_nota_simulado   FOREIGN KEY (simulado_id)   REFERENCES simulado (id),
    CONSTRAINT fk_nota_disciplina FOREIGN KEY (disciplina_id) REFERENCES disciplina (id)
);

-- -------------------------------------------------------
-- Solicitação de retificação de nota
-- -------------------------------------------------------

CREATE TABLE solicitacao_retificacao (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nota_id               BIGINT,
    justificativa         VARCHAR(255),
    justificativa_decisao VARCHAR(255),
    status                ENUM('APROVADA', 'EM_ANALISE', 'PENDENTE', 'REPROVADA')
);

-- -------------------------------------------------------
-- Notificação automática ao responsável sobre risco acadêmico
-- -------------------------------------------------------

CREATE TABLE notificacao_responsavel (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id       BIGINT,
    responsavel_id BIGINT,
    nivel_risco    ENUM('ALTO', 'BAIXO', 'MODERADO'),
    prioridade     ENUM('ALTA', 'MEDIA'),
    mensagem       VARCHAR(255),
    data_criacao   TIMESTAMP(6),
    status         ENUM('LIDA', 'NAO_LIDA')
);
